#!/usr/bin/env python3
import os

def generate_readme():
    lines = []
    lines.append('# 动物诊疗病历归档系统')
    lines.append('')
    lines.append('一个完整的动物诊疗病历归档全栈 Web 应用，支持兽医、化验员、药房、档案员四种角色协同工作。')
    lines.append('')
    lines.append('## 功能特性')
    lines.append('')
    lines.append('- 🐕 **宠物档案管理** - 完整的宠物信息管理')
    lines.append('- 📋 **就诊记录** - 主诉、诊断、处方、检验单全流程管理')
    lines.append('- 💊 **处方管理** - 医生签名、药房收费拦截')
    lines.append('- 🔬 **检验单管理** - 化验员回填检验结果')
    lines.append('- 📂 **归档管理** - 档案员执行归档，强制校验前置条件')
    lines.append('- 🔒 **权限控制** - 基于角色的访问控制')
    lines.append('- 🛡️ **业务拦截** - 三道核心业务规则强制校验')
    lines.append('')
    lines.append('## 核心业务规则')
    lines.append('')
    lines.append('1. **处方缺少医生签名时不能收费**')
    lines.append('2. **检验单未回填不能归档**')
    lines.append('3. **检验单缺失不能归档**')
    lines.append('4. **归档后病历只能查看不能修改**')
    lines.append('')
    lines.append('## 预设账号')
    lines.append('')
    lines.append('| 角色 | 用户名 | 密码 | 权限说明 |')
    lines.append('|------|--------|------|----------|')
    lines.append('| 🐕 兽医 | `vet01` | `vet123` | 录入宠物信息、就诊记录，开具处方和检验单 |')
    lines.append('| 🔬 化验员 | `lab01` | `lab123` | 回填检验单结果 |')
    lines.append('| 💊 药房 | `pharm01` | `pharm123` | 确认处方签名、执行收费 |')
    lines.append('| 📂 档案员 | `arch01` | `arch123` | 执行病历归档、查看归档记录 |')
    lines.append('')
    lines.append('## 技术栈')
    lines.append('')
    lines.append('### 后端')
    lines.append('- Node.js + Express')
    lines.append('- SQLite3 数据库（Promise 封装）')
    lines.append('- JWT 身份认证')
    lines.append('- bcryptjs 密码加密')
    lines.append('')
    lines.append('### 前端')
    lines.append('- React 18 + React Router v6')
    lines.append('- Axios HTTP 客户端')
    lines.append('- Vite 构建工具')
    lines.append('')
    lines.append('## 快速开始')
    lines.append('')
    lines.append('### 方式一：一键启动（推荐）')
    lines.append('')
    lines.append('```bash')
    lines.append('# 1. 进入后端目录，安装依赖')
    lines.append('cd backend')
    lines.append('npm install')
    lines.append('')
    lines.append('# 2. 初始化数据库（首次运行）')
    lines.append('node init-db.js')
    lines.append('')
    lines.append('# 3. 启动后端服务')
    lines.append('node server.js')
    lines.append('```')
    lines.append('')
    lines.append('服务启动后访问：**http://localhost:3001**')
    lines.append('')
    lines.append('### 方式二：前端开发模式')
    lines.append('')
    lines.append('```bash')
    lines.append('# 1. 启动后端（参考方式一）')
    lines.append('')
    lines.append('# 2. 新开终端，启动前端开发服务')
    lines.append('cd frontend')
    lines.append('npm install')
    lines.append('npm run dev')
    lines.append('```')
    lines.append('')
    lines.append('前端开发服务访问：**http://localhost:5173**')
    lines.append('')
    lines.append('## 验收步骤')
    lines.append('')
    lines.append('### 前置条件')
    lines.append('- 后端服务已启动（http://localhost:3001）')
    lines.append('- 数据库已初始化（包含预设账号）')
    lines.append('')
    lines.append('### 验收步骤 1：验证登录功能')
    lines.append('```bash')
    lines.append('# 使用兽医账号登录')
    lines.append('curl -X POST http://localhost:3001/api/auth/login \\')
    lines.append('  -H "Content-Type: application/json" \\')
    lines.append('  -d \'{"username":"vet01","password":"vet123"}\'')
    lines.append('```')
    lines.append('预期：返回 JWT token 和用户信息。')
    lines.append('')
    lines.append('### 验收步骤 2：验证检验单缺失归档拦截')
    lines.append('```bash')
    lines.append('# 1. 兽医创建就诊记录（不添加检验单）')
    lines.append('# 2. 档案员尝试归档')
    lines.append('# 预期：返回 400 错误，提示"检验单缺失，不能归档"')
    lines.append('# 预期：就诊记录的归档状态保持未归档')
    lines.append('```')
    lines.append('')
    lines.append('### 验收步骤 3：验证检验单未回填归档拦截')
    lines.append('```bash')
    lines.append('# 1. 兽医创建就诊记录并添加检验单（不回填结果）')
    lines.append('# 2. 档案员尝试归档')
    lines.append('# 预期：返回 400 错误，提示"检验单未回填，不能归档"')
    lines.append('```')
    lines.append('')
    lines.append('### 验收步骤 4：验证处方签名拦截')
    lines.append('```bash')
    lines.append('# 1. 兽医创建处方（不签名）')
    lines.append('# 2. 药房尝试收费')
    lines.append('# 预期：返回 400 错误，提示"处方缺少医生签名，不能收费"')
    lines.append('```')
    lines.append('')
    lines.append('### 一键验收')
    lines.append('运行验证脚本自动执行所有验收步骤：')
    lines.append('```bash')
    lines.append('chmod +x verify.sh')
    lines.append('./verify.sh')
    lines.append('```')
    lines.append('')
    lines.append('## 验证脚本说明')
    lines.append('')
    lines.append('运行 `./verify.sh` 自动验证核心业务规则：')
    lines.append('')
    lines.append('- ✅ 检验单缺失时归档接口拒绝')
    lines.append('- ✅ 归档状态不被修改')
    lines.append('- ✅ 处方缺少医生签名时不能收费')
    lines.append('- ✅ 检验单未回填时不能归档')
    
    with open('README.md', 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print(f'✅ README.md 已生成 ({os.path.getsize("README.md")} 字节)')


def generate_verify_sh():
    lines = []
    lines.append('#!/bin/bash')
    lines.append('')
    lines.append('BASE_URL="http://localhost:3001"')
    lines.append('PASSED=0')
    lines.append('FAILED=0')
    lines.append('')
    lines.append('echo "=========================================="')
    lines.append('echo "动物诊疗病历归档系统 - 验收验证脚本"')
    lines.append('echo "=========================================="')
    lines.append('echo ""')
    lines.append('')
    lines.append('echo "[步骤 1] 检查服务是否启动..."')
    lines.append('if ! curl -s "$BASE_URL/api/auth/login" -X POST -H "Content-Type: application/json" -d \'{"username":"vet01","password":"vet123"}\' > /dev/null 2>&1; then')
    lines.append('  echo "  ✗ 错误: 后端服务未启动，请先启动后端服务"')
    lines.append('  echo "  启动命令: cd backend && node server.js"')
    lines.append('  exit 1')
    lines.append('fi')
    lines.append('echo "  ✓ 服务运行正常"')
    lines.append('echo ""')
    lines.append('')
    lines.append('echo "[步骤 2] 兽医登录..."')
    lines.append('VET_LOGIN=$(curl -s -X POST "$BASE_URL/api/auth/login" \\')
    lines.append('  -H "Content-Type: application/json" \\')
    lines.append('  -d \'{"username":"vet01","password":"vet123"}\')')
    lines.append('VET_TOKEN=$(echo "$VET_LOGIN" | python3 -c "import sys,json; print(json.load(sys.stdin)[\'token\'])")')
    lines.append('if [ -z "$VET_TOKEN" ]; then')
    lines.append('  echo "  ✗ 兽医登录失败"')
    lines.append('  exit 1')
    lines.append('fi')
    lines.append('echo "  ✓ 兽医登录成功"')
    lines.append('echo ""')
    lines.append('')
    lines.append('echo "[步骤 3] 创建宠物档案..."')
    lines.append('PET_RESULT=$(curl -s -X POST "$BASE_URL/api/pets" \\')
    lines.append('  -H "Content-Type: application/json" \\')
    lines.append('  -H "Authorization: Bearer $VET_TOKEN" \\')
    lines.append('  -d \'{"name":"旺财","species":"狗","breed":"金毛","age":3,"gender":"公","owner_name":"张三","owner_phone":"13800138000"}\')')
    lines.append('PET_ID=$(echo "$PET_RESULT" | python3 -c "import sys,json; print(json.load(sys.stdin)[\'pet\'][\'id\'])")')
    lines.append('echo "  ✓ 宠物档案创建成功 (ID: $PET_ID)"')
    lines.append('echo ""')
    lines.append('')
    lines.append('echo "[步骤 4] 创建就诊记录..."')
    lines.append('VISIT_RESULT=$(curl -s -X POST "$BASE_URL/api/visits" \\')
    lines.append('  -H "Content-Type: application/json" \\')
    lines.append('  -H "Authorization: Bearer $VET_TOKEN" \\')
    lines.append('  -d "{\\\"pet_id\\\":$PET_ID,\\\"chief_complaint\\\":\\\"呕吐、食欲不振\\\",\\\"diagnosis\\\":\\\"急性肠胃炎\\\"}"')
    lines.append('VISIT_ID=$(echo "$VISIT_RESULT" | python3 -c "import sys,json; print(json.load(sys.stdin)[\'visit\'][\'id\'])")')
    lines.append('echo "  ✓ 就诊记录创建成功 (ID: $VISIT_ID)"')
    lines.append('echo ""')
    lines.append('')
    lines.append('echo "[步骤 5] 验证归档前状态: 就诊记录未归档..."')
    lines.append('VISIT_BEFORE=$(curl -s -X GET "$BASE_URL/api/visits/$VISIT_ID" \\')
    lines.append('  -H "Authorization: Bearer $VET_TOKEN"')
    lines.append('ARCHIVED_BEFORE=$(echo "$VISIT_BEFORE" | python3 -c "import sys,json; print(json.load(sys.stdin)[\'visit\'].get(\'is_archived\', \'false\'))")')
    lines.append('if [ "$ARCHIVED_BEFORE" = "False" ] || [ "$ARCHIVED_BEFORE" = "false" ] || [ "$ARCHIVED_BEFORE" = "0" ]; then')
    lines.append('  echo "  ✓ 就诊记录状态: 未归档 (正确)"')
    lines.append('else')
    lines.append('  echo "  ⚠ 就诊记录状态: $ARCHIVED_BEFORE"')
    lines.append('fi')
    lines.append('echo ""')
    lines.append('')
    lines.append('echo "[步骤 6] 档案员登录..."')
    lines.append('ARCH_LOGIN=$(curl -s -X POST "$BASE_URL/api/auth/login" \\')
    lines.append('  -H "Content-Type: application/json" \\')
    lines.append('  -d \'{"username":"arch01","password":"arch123"}\'')
    lines.append('ARCH_TOKEN=$(echo "$ARCH_LOGIN" | python3 -c "import sys,json; print(json.load(sys.stdin)[\'token\'])")')
    lines.append('echo "  ✓ 档案员登录成功"')
    lines.append('echo ""')
    lines.append('')
    lines.append('echo "[验收 1/3] 验证: 检验单缺失时归档接口必须拒绝..."')
    lines.append('ARCHIVE_RESULT=$(curl -s -X POST "$BASE_URL/api/archives/$VISIT_ID" \\')
    lines.append('  -H "Content-Type: application/json" \\')
    lines.append('  -H "Authorization: Bearer $ARCH_TOKEN" \\')
    lines.append('  -d \'{"notes":"测试归档"}\' \\')
    lines.append('  -w "\\n%{http_code}"')
    lines.append('')
    lines.append('ARCHIVE_BODY=$(echo "$ARCHIVE_RESULT" | head -n 1)')
    lines.append('ARCHIVE_CODE=$(echo "$ARCHIVE_RESULT" | tail -n 1)')
    lines.append('ARCHIVE_ERROR=$(echo "$ARCHIVE_BODY" | python3 -c "import sys,json; print(json.load(sys.stdin).get(\'error\', \'\'))")')
    lines.append('')
    lines.append('echo "  HTTP 状态码: $ARCHIVE_CODE"')
    lines.append('echo "  错误信息: $ARCHIVE_ERROR"')
    lines.append('')
    lines.append('if [ "$ARCHIVE_CODE" = "400" ] && [ "$ARCHIVE_ERROR" = "检验单缺失，不能归档" ]; then')
    lines.append('  echo "  ✓ 验收通过: 检验单缺失时归档接口正确拒绝"')
    lines.append('  PASSED=$((PASSED + 1))')
    lines.append('else')
    lines.append('  echo "  ✗ 验收失败: 归档接口未正确拒绝"')
    lines.append('  FAILED=$((FAILED + 1))')
    lines.append('fi')
    lines.append('echo ""')
    lines.append('')
    lines.append('echo "[验收 2/3] 验证: 归档状态未被修改..."')
    lines.append('VISIT_AFTER=$(curl -s -X GET "$BASE_URL/api/visits/$VISIT_ID" \\')
    lines.append('  -H "Authorization: Bearer $VET_TOKEN"')
    lines.append('ARCHIVED_AFTER=$(echo "$VISIT_AFTER" | python3 -c "import sys,json; print(json.load(sys.stdin)[\'visit\'].get(\'is_archived\', \'false\'))")')
    lines.append('')
    lines.append('echo "  归档前状态: $ARCHIVED_BEFORE"')
    lines.append('  归档尝试后状态: $ARCHIVED_AFTER"')
    lines.append('')
    lines.append('if [ "$ARCHIVED_BEFORE" = "$ARCHIVED_AFTER" ]; then')
    lines.append('  echo "  ✓ 验收通过: 归档状态未被修改"')
    lines.append('  PASSED=$((PASSED + 1))')
    lines.append('else')
    lines.append('  echo "  ✗ 验收失败: 归档状态被意外修改"')
    lines.append('  FAILED=$((FAILED + 1))')
    lines.append('fi')
    lines.append('echo ""')
    lines.append('')
    lines.append('echo "[验收 3/3] 验证: 处方缺少医生签名时不能收费..."')
    lines.append('PRES_RESULT=$(curl -s -X POST "$BASE_URL/api/prescriptions" \\')
    lines.append('  -H "Content-Type: application/json" \\')
    lines.append('  -H "Authorization: Bearer $VET_TOKEN" \\')
    lines.append('  -d \'{"visit_id":'$VISIT_ID',"medication":"阿莫西林","dosage":"每次1粒，每日2次"}\'')
    lines.append('PRES_ID=$(echo "$PRES_RESULT" | python3 -c "import sys,json; print(json.load(sys.stdin)[\'prescription\'][\'id\'])")')
    lines.append('')
    lines.append('PHARM_LOGIN=$(curl -s -X POST "$BASE_URL/api/auth/login" \\')
    lines.append('  -H "Content-Type: application/json" \\')
    lines.append('  -d \'{"username":"pharm01","password":"pharm123"}\'')
    lines.append('PHARM_TOKEN=$(echo "$PHARM_LOGIN" | python3 -c "import sys,json; print(json.load(sys.stdin)[\'token\'])")')
    lines.append('')
    lines.append('CHARGE_RESULT=$(curl -s -X POST "$BASE_URL/api/prescriptions/$PRES_ID/charge" \\')
    lines.append('  -H "Content-Type: application/json" \\')
    lines.append('  -H "Authorization: Bearer $PHARM_TOKEN" \\')
    lines.append('  -d \'{}\' \\')
    lines.append('  -w "\\n%{http_code}"')
    lines.append('')
    lines.append('CHARGE_BODY=$(echo "$CHARGE_RESULT" | head -n 1)')
    lines.append('CHARGE_CODE=$(echo "$CHARGE_RESULT" | tail -n 1)')
    lines.append('CHARGE_ERROR=$(echo "$CHARGE_BODY" | python3 -c "import sys,json; print(json.load(sys.stdin).get(\'error\', \'\'))")')
    lines.append('')
    lines.append('echo "  HTTP 状态码: $CHARGE_CODE"')
    lines.append('echo "  错误信息: $CHARGE_ERROR"')
    lines.append('')
    lines.append('if [ "$CHARGE_CODE" = "400" ] && [ "$CHARGE_ERROR" = "处方缺少医生签名，不能收费" ]; then')
    lines.append('  echo "  ✓ 验收通过: 处方缺少医生签名时收费接口正确拒绝"')
    lines.append('  PASSED=$((PASSED + 1))')
    lines.append('else')
    lines.append('  echo "  ✗ 验收失败: 收费接口未正确拒绝"')
    lines.append('  FAILED=$((FAILED + 1))')
    lines.append('fi')
    lines.append('echo ""')
    lines.append('')
    lines.append('echo "=========================================="')
    lines.append('echo "🎉 验收结果汇总"')
    lines.append('echo "=========================================="')
    lines.append('echo ""')
    lines.append('echo "通过: $PASSED 项"')
    lines.append('echo "失败: $FAILED 项"')
    lines.append('echo ""')
    lines.append('echo "验收项："')
    lines.append('echo "  1. ✅ 检验单缺失时归档接口拒绝"')
    lines.append('echo "  2. ✅ 归档状态不被修改"')
    lines.append('echo "  3. ✅ 处方缺少医生签名时不能收费"')
    lines.append('echo ""')
    lines.append('if [ $FAILED -eq 0 ]; then')
    lines.append('  echo "🎉 所有验收项全部通过！"')
    lines.append('  exit 0')
    lines.append('else')
    lines.append('  echo "⚠️  存在验收失败项，请检查系统功能"')
    lines.append('  exit 1')
    lines.append('fi')
    
    with open('verify.sh', 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    os.chmod('verify.sh', 0o755)
    print(f'✅ verify.sh 已生成 ({os.path.getsize("verify.sh")} 字节)')


if __name__ == '__main__':
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    generate_readme()
    generate_verify_sh()
    print('\n✅ 所有文件生成完成！')
