#!/usr/bin/env python3
import os

lines = [
    "#!/bin/bash",
    "",
    "BASE_URL=\"http://localhost:3001\"",
    "PASSED=0",
    "FAILED=0",
    "",
    "echo \"==========================================\"",
    "echo \"动物诊疗病历归档系统 - 验收脚本 (check.sh)\"",
    "echo \"==========================================\"",
    "echo \"\"",
    "",
    "echo \"[前置检查] 验证后端服务...\"",
    "curl -s \"$BASE_URL/api/auth/login\" -X POST -H \"Content-Type: application/json\" -d '{\"username\":\"vet01\",\"password\":\"vet123\"}' > /dev/null 2>&1",
    "if [ $? -ne 0 ]; then",
    "  echo \"  ✗ 错误: 后端服务未启动\"",
    "  echo \"  启动命令: cd backend && node server.js\"",
    "  exit 1",
    "fi",
    "echo \"  ✓ 后端服务运行正常\"",
    "echo \"\"",
    "",
    "echo \"[步骤 1] 兽医登录...\"",
    "VET_LOGIN=$(curl -s -X POST \"$BASE_URL/api/auth/login\" -H \"Content-Type: application/json\" -d '{\"username\":\"vet01\",\"password\":\"vet123\"}')",
    "VET_TOKEN=$(echo \"$VET_LOGIN\" | python3 -c \"import sys,json; print(json.load(sys.stdin)['token'])\")",
    "if [ -z \"$VET_TOKEN\" ]; then",
    "  echo \"  ✗ 兽医登录失败\"",
    "  exit 1",
    "fi",
    "echo \"  ✓ 兽医登录成功\"",
    "echo \"\"",
    "",
    "echo \"==========================================\"",
    "echo \"验收 1/2: 验证归档后病历只读功能\"",
    "echo \"==========================================\"",
    "",
    "PET_RESULT=$(curl -s -X POST \"$BASE_URL/api/pets\" -H \"Content-Type: application/json\" -H \"Authorization: Bearer $VET_TOKEN\" -d '{\"name\":\"验收测试\",\"species\":\"狗\",\"owner_name\":\"测试主人\"}')",
    "PET_ID=$(echo \"$PET_RESULT\" | python3 -c \"import sys,json; print(json.load(sys.stdin)['pet']['id'])\")",
    "echo \"  ✓ 宠物档案创建成功 (ID: $PET_ID)\"",
    "",
    "VISIT_RESULT=$(curl -s -X POST \"$BASE_URL/api/visits\" -H \"Content-Type: application/json\" -H \"Authorization: Bearer $VET_TOKEN\" -d \"{\\\"pet_id\\\":$PET_ID,\\\"chief_complaint\\\":\\\"测试\\\",\\\"diagnosis\\\":\\\"测试\\\"}\")",
    "VISIT_ID=$(echo \"$VISIT_RESULT\" | python3 -c \"import sys,json; print(json.load(sys.stdin)['visit']['id'])\")",
    "echo \"  ✓ 就诊记录创建成功 (ID: $VISIT_ID)\"",
    "",
    "LAB_RESULT=$(curl -s -X POST \"$BASE_URL/api/lab-orders\" -H \"Content-Type: application/json\" -H \"Authorization: Bearer $VET_TOKEN\" -d \"{\\\"visit_id\\\":$VISIT_ID,\\\"test_name\\\":\\\"血常规\\\"}\")",
    "LAB_ID=$(echo \"$LAB_RESULT\" | python3 -c \"import sys,json; print(json.load(sys.stdin)['labOrder']['id'])\")",
    "",
    "LAB_LOGIN=$(curl -s -X POST \"$BASE_URL/api/auth/login\" -H \"Content-Type: application/json\" -d '{\"username\":\"lab01\",\"password\":\"lab123\"}')",
    "LAB_TOKEN=$(echo \"$LAB_LOGIN\" | python3 -c \"import sys,json; print(json.load(sys.stdin)['token'])\")",
    "curl -s -X PUT \"$BASE_URL/api/lab-orders/$LAB_ID/result\" -H \"Content-Type: application/json\" -H \"Authorization: Bearer $LAB_TOKEN\" -d '{\"result\":\"正常\"}' > /dev/null",
    "",
    "ARCH_LOGIN=$(curl -s -X POST \"$BASE_URL/api/auth/login\" -H \"Content-Type: application/json\" -d '{\"username\":\"arch01\",\"password\":\"arch123\"}')",
    "ARCH_TOKEN=$(echo \"$ARCH_LOGIN\" | python3 -c \"import sys,json; print(json.load(sys.stdin)['token'])\")",
    "curl -s -X POST \"$BASE_URL/api/archives/$VISIT_ID\" -H \"Content-Type: application/json\" -H \"Authorization: Bearer $ARCH_TOKEN\" -d '{\"notes\":\"测试\"}' > /dev/null",
    "echo \"  ✓ 就诊记录已归档\"",
    "",
    "UPDATE_RESULT=$(curl -s -X PUT \"$BASE_URL/api/visits/$VISIT_ID\" -H \"Content-Type: application/json\" -H \"Authorization: Bearer $VET_TOKEN\" -d '{\"chief_complaint\":\"修改\",\"diagnosis\":\"修改\"}' -w \"\\n%{http_code}\")",
    "UPDATE_CODE=$(echo \"$UPDATE_RESULT\" | tail -n 1)",
    "UPDATE_BODY=$(echo \"$UPDATE_RESULT\" | head -n 1)",
    "UPDATE_ERROR=$(echo \"$UPDATE_BODY\" | python3 -c \"import sys,json; print(json.load(sys.stdin).get('error', ''))\")",
    "",
    "echo \"  修改 HTTP 状态码: $UPDATE_CODE\"",
    "echo \"  错误信息: $UPDATE_ERROR\"",
    "",
    "if [ \"$UPDATE_CODE\" = \"403\" ] && [[ \"$UPDATE_ERROR\" == *\"已归档\"* ]]; then",
    "  echo \"  ✓ 验收通过: 归档后病历只读功能正常\"",
    "  PASSED=$((PASSED + 1))",
    "else",
    "  echo \"  ✗ 验收失败: 归档后病历仍可修改\"",
    "  FAILED=$((FAILED + 1))",
    "fi",
    "echo \"\"",
    "",
    "echo \"==========================================\"",
    "echo \"验收 2/2: 验证风险复核 API\"",
    "echo \"==========================================\"",
    "",
    "VISITS_COUNT=$(curl -s -X GET \"$BASE_URL/api/visits\" -H \"Authorization: Bearer $VET_TOKEN\" | python3 -c \"import sys,json; print(len(json.load(sys.stdin)['visits']))\")",
    "RISK_COUNT=$(curl -s -X GET \"$BASE_URL/api/risk-review\" -H \"Authorization: Bearer $VET_TOKEN\" | python3 -c \"import sys,json; print(len(json.load(sys.stdin)['visits']))\")",
    "echo \"  就诊记录数量: $VISITS_COUNT\"",
    "echo \"  风险复核数量: $RISK_COUNT\"",
    "",
    "if [ \"$VISITS_COUNT\" = \"$RISK_COUNT\" ]; then",
    "  echo \"  ✓ 验收通过: 风险复核数据与就诊记录一致\"",
    "  PASSED=$((PASSED + 1))",
    "else",
    "  echo \"  ✗ 验收失败: 数据不一致\"",
    "  FAILED=$((FAILED + 1))",
    "fi",
    "",
    "HAS_FLAGS=$(curl -s -X GET \"$BASE_URL/api/risk-review\" -H \"Authorization: Bearer $VET_TOKEN\" | python3 -c \"import sys,json; v=json.load(sys.stdin)['visits']; print('True' if v and 'risk_flags' in v[0] else 'False')\")",
    "if [ \"$HAS_FLAGS\" = \"True\" ]; then",
    "  echo \"  ✓ 验收通过: 风险复核包含风险标记\"",
    "  PASSED=$((PASSED + 1))",
    "else",
    "  echo \"  ✗ 验收失败: 缺少风险标记\"",
    "  FAILED=$((FAILED + 1))",
    "fi",
    "echo \"\"",
    "",
    "echo \"==========================================\"",
    "echo \"🎉 验收结果汇总\"",
    "echo \"==========================================\"",
    "echo \"\"",
    "echo \"通过: $PASSED 项\"",
    "echo \"失败: $FAILED 项\"",
    "echo \"\"",
    "if [ $FAILED -eq 0 ]; then",
    "  echo \"🎉 所有验收项全部通过！\"",
    "  exit 0",
    "else",
    "  echo \"⚠️  存在验收失败项\"",
    "  exit 1",
    "fi",
]

with open("check.sh", "w") as f:
    f.write("\n".join(lines))

os.chmod("check.sh", 0o755)
print("check.sh created successfully!")
